from google import genai
from sql_model import SQLQuery
import os


def generate_sql(client, question, schema, previous_error=None):

    error_context = ""

    if previous_error:
        error_context = f"""
The previous SQL query failed with this error:
{previous_error}

Generate a corrected SQL query that fixes this error.
"""

    prompt = f"""
You are a business data analyst.

Convert the user's question into a SQLite SQL query.

Database schema:
{schema}

Business context:
- revenue represents the revenue generated by each sale, in EUR
- quantity represents the number of units sold
- region represents the country where the sale occurred
- each row represents a sale

{error_context}

User question:
{question}

Return the SQL query in the required structured format.
"""

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt,
        config={
            "response_mime_type": "application/json",
            "response_schema": SQLQuery,
        },
    )

    sql_data = SQLQuery.model_validate_json(response.text)

    return sql_data.sql


def generate_answer(client, question, sql_query, result):
    answer_prompt = f"""
You are a business data analyst.

Answer the user's question using the database result below.

User question:
{question}

SQL query:
{sql_query}

Database result:
{result}

Give a concise answer in natural language.
Do not mention SQL, Python, or the database.
"""

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=answer_prompt
    )

    return response.text