BUSINESS_CONTEXT = """
Dataset: sales

Each row represents one sale.

Fields:
- date: date when the sale occurred, stored as YYYY-MM-DD
- product: product sold
- region: country where the sale occurred
- quantity: number of units sold
- revenue: revenue generated by the sale, in EUR

Business metrics:
- total revenue = SUM(revenue)
- average revenue per sale = AVG(revenue)
- total units sold = SUM(quantity)
- number of sales = COUNT(*)

Date handling:
- date can be filtered using SQLite date functions
- month-based questions should filter using the date range for that month
- year-based questions should filter using the date range for that year

Data limitations:
- the dataset does not contain customer information
- the dataset does not contain order IDs
- the dataset does not contain costs or profit
- the dataset does not contain sales targets
- do not invent columns, tables, or business data that are not present in the schema
"""